version: '3'
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
